@ECHO OFF
SET /A COUNTER = 0
SET /A ITERATIONS = 70
IF %ITERATIONS% GEQ 500 GOTO LOOPEND
IF %ITERATIONS% LEQ 0 GOTO LOOPEND
::START OF LOOP
:LOOPSTART
START
SET /A COUNTER = COUNTER + 1
IF %COUNTER% == %ITERATIONS% GOTO LOOPEND
GOTO LOOPSTART
::END OF LOOP
:LOOPEND
PAUSE